export { Root } from './Root/Root';
export { HomePage } from './HomePage/HomePage';
export { Navbar } from './Navbar/Navbar';
export { Logo } from './Logo/Logo';
export { NotFoundPage } from './NotFoundPage/NotFoundPage';
export { Footer } from './Footer/Footer';
export { Banner as Slider } from './Banner/Banner';
export { HotPrices } from './HotPrices/HotPrices';
export { ProductCard } from './ProductCard/ProductCard';
export { ShopByCategory } from './ShopByCategory/ShopByCategory';
export { CategoryCard } from './CategoryCard/CategoryCard';
export { BrandNewModels } from './BrandNewModels/BrandNewModels';
export { ProductsPage } from './ProductsPage/ProductsPage';
export { ModelPage } from './ModelPage/ModelPage';
export { ProductsSlider as SectionWithCards } from './SectionWithCards/ProductsSlider';
export { TechSpecs } from './TechSpecs/TechSpecs';
export { Price } from './Price/Price';
export { BuyButtons } from './BuyButtons/BuyButtons';
export { FavouritesPage } from './FavouritesPage/FavouritesPage';
export { CartPage } from './CartPage';
