export const colorReplacementMap: Record<string, string> = {
  rosegold: 'lightpink',
  'rose gold': 'lightpink',
  spacegray: '#515151',
  'space gray': '#515151',
  graphite: '#515151',
  midnight: 'darkblue',
  spaceblack: 'black',
  sierrablue: 'steelblue',
  midnightgreen: 'darkgreen',
  spacegold: 'gold',
  skyblue: 'lightblue',
  'sky blue': 'lightblue',
  starlight: 'beige',
};
