export enum ActionTypes {
  SET_PHONES = 'SET_PHONES',
  SET_LOADING = 'SET__LOADING',
  SET_SORT_BY = 'SET_SORT_BY',
  SET_QUERY = 'SET_QUERY',
  ADD_FAVOURITES = 'ADD_FAVOURITES',
  ADD_TO_CART = 'ADD_TO_CART',
}
