export enum ActionTypes {
  SET_PHONES = 'SET_PHONES',
  SET_DETAILS = 'SET_DETAILS',
  SET_LOADING_PHONES = 'SET__LOADING_PHONES',
  SET_LOADING_DETAILS = 'SET__LOADING_DETAILS',
  SET_SORT_BY = 'SET_SORT_BY',
  SET_QUERY = 'SET_QUERY',
  ADD_FAVOURITES = 'ADD_FAVOURITES',
  ADD_TO_CART = 'ADD_TO_CART',
}
