export enum IconList {
  cart = 'Cart',
  down = 'Chevron-Down',
  downDisabled = 'Chevron-Down-disabled',
  left = 'Chevron-Left',
  leftDisabled = 'Chevron-Left-disabled',
  right = 'Chevron-Right',
  rightDisabled = 'Chevron-Right-disabled',
  up = 'Chevron-Up',
  upDisabled = 'Chevron-Up-disabled',
  close = 'Close',
  favoritesFillde = 'Favourites-Filled',
  favorites = 'Favourites',
  home = 'Home',
  menu = 'Menu',
  minus = 'Minus',
  plus = 'Plus',
  search = 'Search',
}
