import type { TeamMember } from '../types/teamMember';

export const TEAM_MEMBERS: TeamMember[] = [
  {
    name: 'Artem Stadnik',
    position: 'Tech Lead',
    descriptionKey: 'team.artem_stadnik',
    photo: 'https://ik.imagekit.io/ox4rssyih/img/contacts/artem-stadnik.JPG',
    gradient: 'from-violet-500 to-indigo-600',
    telegram: 'https://t.me/stadnika',
    email: 'mailto:artem.stadnik.contact@gmail.com',
    github: 'https://github.com/artemstadnik',
    linkedin: 'https://linkedin.com/in/artem-stadnik/',
  },
  {
    name: 'Artem Yurin',
    position: 'Project Manager',
    descriptionKey: 'team.artem_yurin',
    photo: 'https://ik.imagekit.io/ox4rssyih/img/contacts/artem-yurin.JPG',
    gradient: 'from-sky-500 to-cyan-600',
    telegram: 'https://t.me/Aartema_A',
    email: 'mailto:fs.artem.yurin@gmail.com',
    github: 'https://github.com/Br0No',
    linkedin: 'https://linkedin.com/in/artem-yurin-75b92b3ab/',
  },
  {
    name: 'Diana Kerekesha',
    position: 'Full-stack Developer',
    descriptionKey: 'team.diana_kerekesha',
    photo: 'https://ik.imagekit.io/ox4rssyih/img/contacts/diana-kerekesha.JPG',
    gradient: 'from-emerald-400 to-teal-600',
    telegram: 'https://t.me/dianakerekesha',
    email: 'mailto:diana.kerekesha.fs@gmail.com',
    github: 'https://github.com/dianakerekesha',
    linkedin: 'https://linkedin.com/in/diana-kerekesha',
  },
  {
    name: 'Taras Demianiuk',
    position: 'Full-stack Developer',
    descriptionKey: 'team.taras_demianiuk',
    photo: 'https://ik.imagekit.io/ox4rssyih/img/contacts/taras-demianiuk.JPG',
    gradient: 'from-amber-400 to-orange-500',
    telegram: 'https://t.me/Demtar23',
    email: 'mailto:demtaras1@gmail.com',
    github: 'https://github.com/Demtar23',
    linkedin: 'https://linkedin.com/in/taras-demianiuk/',
  },
  {
    name: 'Alina Khvorostian',
    position: 'Frontend Developer',
    descriptionKey: 'team.alina_khvorostian',
    photo:
      'https://ik.imagekit.io/ox4rssyih/img/contacts/alina-khvorostian.jpg',
    gradient: 'from-rose-400 to-pink-600',
    telegram: 'https://t.me/AlinaKhvorostian',
    email: 'mailto:a.khvarastyan@gmail.com',
    github: 'https://github.com/akhvarastyan-web',
    linkedin: 'https://linkedin.com/in/',
  },
];
