import type { ColorKey } from '../types/ColorKey';

export const colorKeys = [
  'black',
  'gold',
  'silver',
  'green',
  'yellow',
  'white',
  'purple',
  'red',
  'midnightgreen',
  'coral',
  'midnight',
  'spaceblack',
  'blue',
  'pink',
  'graphite',
  'sierrablue',
  'spacegray',
  'space gray',
  'space-gray',
  'rosegold',
  'rosegold',
  'rose-gold',
  'rose gold',
  'sky-blue',
  'skyblue',
  'sky blue',
  'starlight',
];

export const appleColorsHex: Record<ColorKey, string> = {
  'black': '#000000',
  'rosegold': '#B76E79',
  'rose-gold': '#B76E79',
  'rose gold': '#B76E79',
  'gold': '#D6AB7A',
  'silver': '#C0C0C0',
  'spacegray': '#4B4B4B',
  'space gray': '#4B4B4B',
  'space-gray': '#4B4B4B',
  'green': '#ADE0C5',
  'yellow': '#FFFF00',
  'white': '#FFFFFF',
  'purple': '#BA95BA',
  'red': '#FF0000',
  'midnightgreen': '#004953',
  'coral': '#FF7F50',
  'midnight': '#191970',
  'spaceblack': '#1C1C1C',
  'blue': '#0000FF',
  'pink': '#FFC0CB',
  'graphite': '#383838',
  'sierrablue': '#5A9BD4',
  'starlight': '#F5F5DC',
  'sky-blue': '#87CEEB',
  'skyblue': '#87CEEB',
  'sky blue': '#87CEEB',
};

export const allAvailableCapacity = [
  '32gb',
  '64gb',
  '128gb',
  '256gb',
  '512gb',
  '1tb',
  '2tb',
  '38mm',
  '42mm',
  '40mm',
  '44mm',
];
