export const SET_PHONE_DETAILS = 'SET_PHONE_DETAILS';
export const SET_PHONES = 'SET_PHONES';
export const TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const SUBSTRACT_QUANTITY = 'SUBSTRACT_QUANTITY';
