export const PhonePage = () => {
  return (
    <div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
      <div>PHONE PAGE</div>
    </div>
  );
};
