/* eslint-disable */


export const newPhoneArray = [
  {
    id: 10001,
    picsArray: [
      "./img/products/folder1/newPhone1.svg",
      "./img/products/folder1/newImg1.svg",
      "./img/products/folder1/image8.svg",
      "./img/products/folder1/newImg2.svg",
      "./img/products/folder1/newImg1.svg",
    ],
    picsArray2: [
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
    ],
    picsArray3: [
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
    ],
    picsArray4: [
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
    ],
    name: 'Apple iPhone 11 Pro Max 64GB Gold (iMT9G2FS/A) ID 10001',
    priceFull: '$1199',
    priceDiscount: '$1099',
    description1: 'Screen/62.5" OLED',
    description2: 'Capacity/64 GB',
    description3: 'Ram/4 GB',
    textAbout: 'And then there was Pro/A transformative triple‑camera system that adds tons of capability without complexity./An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro./Camera/Meet the first triple‑camera system to combine cutting‑edge technology with the legendary simplicity of iPhone. Capture up to four times more scene. Get beautiful images in drastically lower light. Shoot the highest‑quality video in a smartphone — then edit with the same tools you love for photos. You’ve never shot with anything like it./Shoot it. Flip it. Zoom it. Crop it. Cut it. Light it. Tweak it. Love it./iPhone 11 Pro lets you capture videos that are beautifully true to life, with greater detail and smoother motion. Epic processing power means it can shoot 4K video with extended dynamic range and cinematic video stabilization — all at 60 fps. You get more creative control, too, with four times more scene and powerful new editing tools to play with.',
    tehcSpecs: 'Screen/62.5” OLED/Resolution/2688x1242/Processor/Apple A12 Bionic/RAM/3 GB/Built in memory/64 GB/Camera/12 Mp + 12 Mp + 12 Mp (Triple)/Zoom/Optical, 2x/Cell/GSM, LTE, UMTS',
    like: false,
    addedToCart: false,
  },
  {
    id: 10002,
    picsArray: [
      "./img/products/folder1/newPhone2.svg",
      "./img/products/folder1/newImg1.svg",
      "./img/products/folder1/image8.svg",
      "./img/products/folder1/newImg2.svg",
      "./img/products/folder1/newImg1.svg",
    ],
    picsArray2: [
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
    ],
    picsArray3: [
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
    ],
    picsArray4: [
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
    ],
    name: 'Apple iPhone 19 128GB Purple (iMT9G2FS/A)',
    priceFull: '$899',
    priceDiscount: '$799',
    description1: 'Screen/12.2" OLED',
    description2: 'Capacity/128 GB',
    description3: 'Ram/4 GB',
    textAbout: 'And then there was Pro/A transformative triple‑camera system that adds tons of capability without complexity./An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro./Camera/Meet the first triple‑camera system to combine cutting‑edge technology with the legendary simplicity of iPhone. Capture up to four times more scene. Get beautiful images in drastically lower light. Shoot the highest‑quality video in a smartphone — then edit with the same tools you love for photos. You’ve never shot with anything like it./Shoot it. Flip it. Zoom it. Crop it. Cut it. Light it. Tweak it. Love it./iPhone 11 Pro lets you capture videos that are beautifully true to life, with greater detail and smoother motion. Epic processing power means it can shoot 4K video with extended dynamic range and cinematic video stabilization — all at 60 fps. You get more creative control, too, with four times more scene and powerful new editing tools to play with.',
    tehcSpecs: 'Screen/12.2” OLED/Resolution/2688x1242/Processor/Apple A16 Bionic/RAM/4 GB/Built in memory/128 GB/Camera/66 Mp + 65 Mp + 99 Mp (Triple)/Zoom/Optical, 9x/Cell/GSM, LTE, UMTS',
    like: false,
    addedToCart: false,
  },
  {
    id: 10003,
    picsArray: [
      "./img/products/folder1/newPhone3.svg",
      "./img/products/folder1/newImg1.svg",
      "./img/products/folder1/image8.svg",
      "./img/products/folder1/newImg2.svg",
      "./img/products/folder1/newImg1.svg",
    ],
    picsArray2: [
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
    ],
    picsArray3: [
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
    ],
    picsArray4: [
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
    ],
    name: 'Apple iPhone Xs 64GB Silver (iMT9G2FS/A)',
    priceFull: '$899',
    priceDiscount: '$799',
    description1: 'Screen/52.8" GB',
    description2: 'Capacity/64 GB',
    description3: 'Ram/4 GB',
    textAbout: 'And then there was Pro/A transformative triple‑camera system that adds tons of capability without complexity./An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro./Camera/Meet the first triple‑camera system to combine cutting‑edge technology with the legendary simplicity of iPhone. Capture up to four times more scene. Get beautiful images in drastically lower light. Shoot the highest‑quality video in a smartphone — then edit with the same tools you love for photos. You’ve never shot with anything like it./Shoot it. Flip it. Zoom it. Crop it. Cut it. Light it. Tweak it. Love it./iPhone 11 Pro lets you capture videos that are beautifully true to life, with greater detail and smoother motion. Epic processing power means it can shoot 4K video with extended dynamic range and cinematic video stabilization — all at 60 fps. You get more creative control, too, with four times more scene and powerful new editing tools to play with.',
    tehcSpecs: 'Screen/52.8” OLED/Resolution/2688x1242/Processor/Apple A12 Bionic/RAM/4 GB/Built in memory/64 GB/Camera/76 Mp + 82 Mp + 92 Mp (Triple)/Zoom/Optical, 2x/Cell/GSM, LTE, UMTS',
    like: false,
    addedToCart: false,
  },
  {
    id: 10004,
    picsArray: [
      "./img/products/folder1/newPhone4.svg",
      "./img/products/folder1/newImg1.svg",
      "./img/products/folder1/image8.svg",
      "./img/products/folder1/newImg2.svg",
      "./img/products/folder1/newImg1.svg",
    ],
    picsArray2: [
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
    ],
    picsArray3: [
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
    ],
    picsArray4: [
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
    ],
    name: 'Apple iPhone 2 Pro Max 512GB Midnight Green (iMT9G2FS/A)',
    priceFull: '',
    priceDiscount: '$1299',
    description1: 'Screen/16.5" OLED',
    description2: 'Capacity/512 GB',
    description3: 'Ram/4 GB',
    textAbout: 'And then there was Pro/A transformative triple‑camera system that adds tons of capability without complexity./An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro./Camera/Meet the first triple‑camera system to combine cutting‑edge technology with the legendary simplicity of iPhone. Capture up to four times more scene. Get beautiful images in drastically lower light. Shoot the highest‑quality video in a smartphone — then edit with the same tools you love for photos. You’ve never shot with anything like it./Shoot it. Flip it. Zoom it. Crop it. Cut it. Light it. Tweak it. Love it./iPhone 11 Pro lets you capture videos that are beautifully true to life, with greater detail and smoother motion. Epic processing power means it can shoot 4K video with extended dynamic range and cinematic video stabilization — all at 60 fps. You get more creative control, too, with four times more scene and powerful new editing tools to play with.',
    tehcSpecs: 'Screen/16.5” OLED/Resolution/2688x1242/Processor/Apple A12 Bionic/RAM/4 GB/Built in memory/512 GB/Camera/69 Mp + 88 Mp + 99 Mp (Triple)/Zoom/Optical, 2x/Cell/GSM, LTE, UMTS',
    like: false,
    addedToCart: false,
  },
  {
    id: 10005,
    picsArray: [
      "./img/products/folder1/newPhone5.svg",
      "./img/products/folder1/newImg1.svg",
      "./img/products/folder1/image8.svg",
      "./img/products/folder1/newImg2.svg",
      "./img/products/folder1/newImg1.svg",
    ],
    picsArray2: [
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
    ],
    picsArray3: [
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
    ],
    picsArray4: [
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
    ],
    name: 'Apple iPhone 113 128GB (Product) Red (iMT9G2FS/A)',
    priceFull: '',
    priceDiscount: '$999',
    description1: 'Screen/11.2" OLED',
    description2: 'Capacity/128 GB',
    description3: 'Ram/4 GB',
    textAbout: 'And then there was Pro/A transformative triple‑camera system that adds tons of capability without complexity./An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro./Camera/Meet the first triple‑camera system to combine cutting‑edge technology with the legendary simplicity of iPhone. Capture up to four times more scene. Get beautiful images in drastically lower light. Shoot the highest‑quality video in a smartphone — then edit with the same tools you love for photos. You’ve never shot with anything like it./Shoot it. Flip it. Zoom it. Crop it. Cut it. Light it. Tweak it. Love it./iPhone 11 Pro lets you capture videos that are beautifully true to life, with greater detail and smoother motion. Epic processing power means it can shoot 4K video with extended dynamic range and cinematic video stabilization — all at 60 fps. You get more creative control, too, with four times more scene and powerful new editing tools to play with.',
    tehcSpecs: 'Screen/11.2” OLED/Resolution/2688x1242/Processor/Apple A182 Shmionic/RAM/4 GB/Built in memory/128 GB/Camera/55 Mp + 88 Mp + 99 Mp (Triple)/Zoom/Optical, 9x/Cell/GSM, LTE, UMTS',
    like: false,
    addedToCart: false,
  },
  {
    id: 10006,
    picsArray: [
      "./img/products/folder1/newPhone1.svg",
      "./img/products/folder1/newImg1.svg",
      "./img/products/folder1/image8.svg",
      "./img/products/folder1/newImg2.svg",
      "./img/products/folder1/newImg1.svg",
    ],
    picsArray2: [
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
    ],
    picsArray3: [
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
    ],
    picsArray4: [
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
    ],
    name: 'Apple iPhone 11 Pro Max 64GB Gold (iMT9G2FS/A) ID 10001',
    priceFull: '$1199',
    priceDiscount: '$1099',
    description1: 'Screen/6.5" OLED',
    description2: 'Capacity/64 GB',
    description3: 'Ram/4 GB',
    textAbout: 'And then there was Pro/A transformative triple‑camera system that adds tons of capability without complexity./An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro./Camera/Meet the first triple‑camera system to combine cutting‑edge technology with the legendary simplicity of iPhone. Capture up to four times more scene. Get beautiful images in drastically lower light. Shoot the highest‑quality video in a smartphone — then edit with the same tools you love for photos. You’ve never shot with anything like it./Shoot it. Flip it. Zoom it. Crop it. Cut it. Light it. Tweak it. Love it./iPhone 11 Pro lets you capture videos that are beautifully true to life, with greater detail and smoother motion. Epic processing power means it can shoot 4K video with extended dynamic range and cinematic video stabilization — all at 60 fps. You get more creative control, too, with four times more scene and powerful new editing tools to play with.',
    tehcSpecs: 'Screen/6.5” OLED/Resolution/2688x1242/Processor/Apple A12 Bionic/RAM/3 GB/Built in memory/64 GB/Camera/12 Mp + 12 Mp + 12 Mp (Triple)/Zoom/Optical, 2x/Cell/GSM, LTE, UMTS',
    like: false,
    addedToCart: false,
  },
  {
    id: 10007,
    picsArray: [
      "./img/products/folder1/newPhone2.svg",
      "./img/products/folder1/newImg1.svg",
      "./img/products/folder1/image8.svg",
      "./img/products/folder1/newImg2.svg",
      "./img/products/folder1/newImg1.svg",
    ],
    picsArray2: [
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
    ],
    picsArray3: [
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
    ],
    picsArray4: [
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
    ],
    name: 'Apple iPhone 19 128GB Purple (iMT9G2FS/A)',
    priceFull: '$899',
    priceDiscount: '$799',
    description1: 'Screen/6.2" OLED',
    description2: 'Capacity/128 GB',
    description3: 'Ram/4 GB',
    textAbout: 'And then there was Pro/A transformative triple‑camera system that adds tons of capability without complexity./An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro./Camera/Meet the first triple‑camera system to combine cutting‑edge technology with the legendary simplicity of iPhone. Capture up to four times more scene. Get beautiful images in drastically lower light. Shoot the highest‑quality video in a smartphone — then edit with the same tools you love for photos. You’ve never shot with anything like it./Shoot it. Flip it. Zoom it. Crop it. Cut it. Light it. Tweak it. Love it./iPhone 11 Pro lets you capture videos that are beautifully true to life, with greater detail and smoother motion. Epic processing power means it can shoot 4K video with extended dynamic range and cinematic video stabilization — all at 60 fps. You get more creative control, too, with four times more scene and powerful new editing tools to play with.',
    tehcSpecs: 'Screen/6.2” OLED/Resolution/2688x1242/Processor/Apple A1276 Bionic/RAM/4 GB/Built in memory/128 GB/Camera/66 Mp + 65 Mp + 99 Mp (Triple)/Zoom/Optical, 9x/Cell/GSM, LTE, UMTS',
    like: false,
    addedToCart: false,
  },
  {
    id: 10008,
    picsArray: [
      "./img/products/folder1/newPhone3.svg",
      "./img/products/folder1/newImg1.svg",
      "./img/products/folder1/image8.svg",
      "./img/products/folder1/newImg2.svg",
      "./img/products/folder1/newImg1.svg",
    ],
    picsArray2: [
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
    ],
    picsArray3: [
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
    ],
    picsArray4: [
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
    ],
    name: 'Apple iPhone Xs 64GB Silver (iMT9G2FS/A)',
    priceFull: '$899',
    priceDiscount: '$799',
    description1: 'Screen/5.8" GB',
    description2: 'Capacity/64 GB',
    description3: 'Ram/4 GB',
    textAbout: 'And then there was Pro/A transformative triple‑camera system that adds tons of capability without complexity./An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro./Camera/Meet the first triple‑camera system to combine cutting‑edge technology with the legendary simplicity of iPhone. Capture up to four times more scene. Get beautiful images in drastically lower light. Shoot the highest‑quality video in a smartphone — then edit with the same tools you love for photos. You’ve never shot with anything like it./Shoot it. Flip it. Zoom it. Crop it. Cut it. Light it. Tweak it. Love it./iPhone 11 Pro lets you capture videos that are beautifully true to life, with greater detail and smoother motion. Epic processing power means it can shoot 4K video with extended dynamic range and cinematic video stabilization — all at 60 fps. You get more creative control, too, with four times more scene and powerful new editing tools to play with.',
    tehcSpecs: 'Screen/5.8” OLED/Resolution/2688x1242/Processor/Apple A11 Bionic/RAM/4 GB/Built in memory/64 GB/Camera/76 Mp + 82 Mp + 92 Mp (Triple)/Zoom/Optical, 2x/Cell/GSM, LTE, UMTS',
    like: false,
    addedToCart: false,
  },
  {
    id: 10009,
    picsArray: [
      "./img/products/folder1/newPhone4.svg",
      "./img/products/folder1/newImg1.svg",
      "./img/products/folder1/image8.svg",
      "./img/products/folder1/newImg2.svg",
      "./img/products/folder1/newImg1.svg",
    ],
    picsArray2: [
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
    ],
    picsArray3: [
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
    ],
    picsArray4: [
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
    ],
    name: 'Apple iPhone 2 Pro Max 512GB Midnight Green (iMT9G2FS/A)',
    priceFull: '',
    priceDiscount: '$1299',
    description1: 'Screen/6.5" OLED',
    description2: 'Capacity/512 GB',
    description3: 'Ram/4 GB',
    textAbout: 'And then there was Pro/A transformative triple‑camera system that adds tons of capability without complexity./An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro./Camera/Meet the first triple‑camera system to combine cutting‑edge technology with the legendary simplicity of iPhone. Capture up to four times more scene. Get beautiful images in drastically lower light. Shoot the highest‑quality video in a smartphone — then edit with the same tools you love for photos. You’ve never shot with anything like it./Shoot it. Flip it. Zoom it. Crop it. Cut it. Light it. Tweak it. Love it./iPhone 11 Pro lets you capture videos that are beautifully true to life, with greater detail and smoother motion. Epic processing power means it can shoot 4K video with extended dynamic range and cinematic video stabilization — all at 60 fps. You get more creative control, too, with four times more scene and powerful new editing tools to play with.',
    tehcSpecs: 'Screen/6.5” OLED/Resolution/2688x1242/Processor/Apple A12 Bionic/RAM/4 GB/Built in memory/512 GB/Camera/69 Mp + 88 Mp + 99 Mp (Triple)/Zoom/Optical, 2x/Cell/GSM, LTE, UMTS',
    like: false,
    addedToCart: false,
  },
  {
    id: 10010,
    picsArray: [
      "./img/products/folder1/newPhone5.svg",
      "./img/products/folder1/newImg1.svg",
      "./img/products/folder1/image8.svg",
      "./img/products/folder1/newImg2.svg",
      "./img/products/folder1/newImg1.svg",
    ],
    picsArray2: [
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
    ],
    picsArray3: [
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
    ],
    picsArray4: [
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
    ],
    name: 'Apple iPhone 113 128GB (Product) Red (iMT9G2FS/A)',
    priceFull: '',
    priceDiscount: '$999',
    description1: 'Screen/6.2" OLED',
    description2: 'Capacity/128 GB',
    description3: 'Ram/4 GB',
    textAbout: 'And then there was Pro/A transformative triple‑camera system that adds tons of capability without complexity./An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro./Camera/Meet the first triple‑camera system to combine cutting‑edge technology with the legendary simplicity of iPhone. Capture up to four times more scene. Get beautiful images in drastically lower light. Shoot the highest‑quality video in a smartphone — then edit with the same tools you love for photos. You’ve never shot with anything like it./Shoot it. Flip it. Zoom it. Crop it. Cut it. Light it. Tweak it. Love it./iPhone 11 Pro lets you capture videos that are beautifully true to life, with greater detail and smoother motion. Epic processing power means it can shoot 4K video with extended dynamic range and cinematic video stabilization — all at 60 fps. You get more creative control, too, with four times more scene and powerful new editing tools to play with.',
    tehcSpecs: 'Screen/6.2” OLED/Resolution/2688x1242/Processor/Apple A182 Shmionic/RAM/4 GB/Built in memory/128 GB/Camera/55 Mp + 88 Mp + 99 Mp (Triple)/Zoom/Optical, 9x/Cell/GSM, LTE, UMTS',
    like: false,
    addedToCart: false,
  },
  {
    id: 10011,
    picsArray: [
      "./img/products/folder1/newPhone1.svg",
      "./img/products/folder1/newImg1.svg",
      "./img/products/folder1/image8.svg",
      "./img/products/folder1/newImg2.svg",
      "./img/products/folder1/newImg1.svg",
    ],
    picsArray2: [
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
    ],
    picsArray3: [
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
    ],
    picsArray4: [
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
    ],
    name: 'Apple iPhone 11 Pro Max 64GB Gold (iMT9G2FS/A) ID 10001',
    priceFull: '$1199',
    priceDiscount: '$1099',
    description1: 'Screen/6.5" OLED',
    description2: 'Capacity/64 GB',
    description3: 'Ram/4 GB',
    textAbout: 'And then there was Pro/A transformative triple‑camera system that adds tons of capability without complexity./An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro./Camera/Meet the first triple‑camera system to combine cutting‑edge technology with the legendary simplicity of iPhone. Capture up to four times more scene. Get beautiful images in drastically lower light. Shoot the highest‑quality video in a smartphone — then edit with the same tools you love for photos. You’ve never shot with anything like it./Shoot it. Flip it. Zoom it. Crop it. Cut it. Light it. Tweak it. Love it./iPhone 11 Pro lets you capture videos that are beautifully true to life, with greater detail and smoother motion. Epic processing power means it can shoot 4K video with extended dynamic range and cinematic video stabilization — all at 60 fps. You get more creative control, too, with four times more scene and powerful new editing tools to play with.',
    tehcSpecs: 'Screen/6.5” OLED/Resolution/2688x1242/Processor/Apple A12 Bionic/RAM/3 GB/Built in memory/64 GB/Camera/12 Mp + 12 Mp + 12 Mp (Triple)/Zoom/Optical, 2x/Cell/GSM, LTE, UMTS',
    like: false,
    addedToCart: false,
  },
  {
    id: 10012,
    picsArray: [
      "./img/products/folder1/newPhone2.svg",
      "./img/products/folder1/newImg1.svg",
      "./img/products/folder1/image8.svg",
      "./img/products/folder1/newImg2.svg",
      "./img/products/folder1/newImg1.svg",
    ],
    picsArray2: [
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
    ],
    picsArray3: [
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
    ],
    picsArray4: [
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
    ],
    name: 'Apple iPhone 19 128GB Purple (iMT9G2FS/A)',
    priceFull: '$899',
    priceDiscount: '$799',
    description1: 'Screen/6.2" OLED',
    description2: 'Capacity/128 GB',
    description3: 'Ram/4 GB',
    textAbout: 'And then there was Pro/A transformative triple‑camera system that adds tons of capability without complexity./An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro./Camera/Meet the first triple‑camera system to combine cutting‑edge technology with the legendary simplicity of iPhone. Capture up to four times more scene. Get beautiful images in drastically lower light. Shoot the highest‑quality video in a smartphone — then edit with the same tools you love for photos. You’ve never shot with anything like it./Shoot it. Flip it. Zoom it. Crop it. Cut it. Light it. Tweak it. Love it./iPhone 11 Pro lets you capture videos that are beautifully true to life, with greater detail and smoother motion. Epic processing power means it can shoot 4K video with extended dynamic range and cinematic video stabilization — all at 60 fps. You get more creative control, too, with four times more scene and powerful new editing tools to play with.',
    tehcSpecs: 'Screen/6.2” OLED/Resolution/2688x1242/Processor/Apple A1276 Bionic/RAM/4 GB/Built in memory/128 GB/Camera/66 Mp + 65 Mp + 99 Mp (Triple)/Zoom/Optical, 9x/Cell/GSM, LTE, UMTS',
    like: false,
    addedToCart: false,
  },
  {
    id: 10013,
    picsArray: [
      "./img/products/folder1/newPhone3.svg",
      "./img/products/folder1/newImg1.svg",
      "./img/products/folder1/image8.svg",
      "./img/products/folder1/newImg2.svg",
      "./img/products/folder1/newImg1.svg",
    ],
    picsArray2: [
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
    ],
    picsArray3: [
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
    ],
    picsArray4: [
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
    ],
    name: 'Apple iPhone Xs 64GB Silver (iMT9G2FS/A)',
    priceFull: '$899',
    priceDiscount: '$799',
    description1: 'Screen/5.8" GB',
    description2: 'Capacity/64 GB',
    description3: 'Ram/4 GB',
    textAbout: 'And then there was Pro/A transformative triple‑camera system that adds tons of capability without complexity./An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro./Camera/Meet the first triple‑camera system to combine cutting‑edge technology with the legendary simplicity of iPhone. Capture up to four times more scene. Get beautiful images in drastically lower light. Shoot the highest‑quality video in a smartphone — then edit with the same tools you love for photos. You’ve never shot with anything like it./Shoot it. Flip it. Zoom it. Crop it. Cut it. Light it. Tweak it. Love it./iPhone 11 Pro lets you capture videos that are beautifully true to life, with greater detail and smoother motion. Epic processing power means it can shoot 4K video with extended dynamic range and cinematic video stabilization — all at 60 fps. You get more creative control, too, with four times more scene and powerful new editing tools to play with.',
    tehcSpecs: 'Screen/5.8” OLED/Resolution/2688x1242/Processor/Apple A12 Bionic/RAM/4 GB/Built in memory/64 GB/Camera/76 Mp + 82 Mp + 92 Mp (Triple)/Zoom/Optical, 2x/Cell/GSM, LTE, UMTS',
    like: false,
    addedToCart: false,
  },
  {
    id: 10014,
    picsArray: [
      "./img/products/folder1/newPhone4.svg",
      "./img/products/folder1/newImg1.svg",
      "./img/products/folder1/image8.svg",
      "./img/products/folder1/newImg2.svg",
      "./img/products/folder1/newImg1.svg",
    ],
    picsArray2: [
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
    ],
    picsArray3: [
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
    ],
    picsArray4: [
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
    ],
    name: 'Apple iPhone 2 Pro Max 512GB Midnight Green (iMT9G2FS/A)',
    priceFull: '',
    priceDiscount: '$1299',
    description1: 'Screen/6.5" OLED',
    description2: 'Capacity/512 GB',
    description3: 'Ram/4 GB',
    textAbout: 'And then there was Pro/A transformative triple‑camera system that adds tons of capability without complexity./An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro./Camera/Meet the first triple‑camera system to combine cutting‑edge technology with the legendary simplicity of iPhone. Capture up to four times more scene. Get beautiful images in drastically lower light. Shoot the highest‑quality video in a smartphone — then edit with the same tools you love for photos. You’ve never shot with anything like it./Shoot it. Flip it. Zoom it. Crop it. Cut it. Light it. Tweak it. Love it./iPhone 11 Pro lets you capture videos that are beautifully true to life, with greater detail and smoother motion. Epic processing power means it can shoot 4K video with extended dynamic range and cinematic video stabilization — all at 60 fps. You get more creative control, too, with four times more scene and powerful new editing tools to play with.',
    tehcSpecs: 'Screen/6.5” OLED/Resolution/2688x1242/Processor/Apple A12 Bionic/RAM/4 GB/Built in memory/512 GB/Camera/69 Mp + 88 Mp + 99 Mp (Triple)/Zoom/Optical, 2x/Cell/GSM, LTE, UMTS',
    like: false,
    addedToCart: false,
  },
  {
    id: 10015,
    picsArray: [
      "./img/products/folder1/newPhone5.svg",
      "./img/products/folder1/newImg1.svg",
      "./img/products/folder1/image8.svg",
      "./img/products/folder1/newImg2.svg",
      "./img/products/folder1/newImg1.svg",
    ],
    picsArray2: [
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
    ],
    picsArray3: [
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
    ],
    picsArray4: [
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
    ],
    name: 'Apple iPhone 113 128GB (Product) Red (iMT9G2FS/A)',
    priceFull: '',
    priceDiscount: '$999',
    description1: 'Screen/6.2" OLED',
    description2: 'Capacity/128 GB',
    description3: 'Ram/4 GB',
    textAbout: 'And then there was Pro/A transformative triple‑camera system that adds tons of capability without complexity./An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro./Camera/Meet the first triple‑camera system to combine cutting‑edge technology with the legendary simplicity of iPhone. Capture up to four times more scene. Get beautiful images in drastically lower light. Shoot the highest‑quality video in a smartphone — then edit with the same tools you love for photos. You’ve never shot with anything like it./Shoot it. Flip it. Zoom it. Crop it. Cut it. Light it. Tweak it. Love it./iPhone 11 Pro lets you capture videos that are beautifully true to life, with greater detail and smoother motion. Epic processing power means it can shoot 4K video with extended dynamic range and cinematic video stabilization — all at 60 fps. You get more creative control, too, with four times more scene and powerful new editing tools to play with.',
    tehcSpecs: 'Screen/6.2” OLED/Resolution/2688x1242/Processor/Apple A182 Shmionic/RAM/4 GB/Built in memory/128 GB/Camera/55 Mp + 88 Mp + 99 Mp (Triple)/Zoom/Optical, 9x/Cell/GSM, LTE, UMTS',
    like: false,
    addedToCart: false,
  },
  {
    id: 10016,
    picsArray: [
      "./img/products/folder1/newPhone1.svg",
      "./img/products/folder1/newImg1.svg",
      "./img/products/folder1/image8.svg",
      "./img/products/folder1/newImg2.svg",
      "./img/products/folder1/newImg1.svg",
    ],
    picsArray2: [
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
    ],
    picsArray3: [
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
    ],
    picsArray4: [
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
    ],
    name: 'Apple iPhone 11 Pro Max 64GB Gold (iMT9G2FS/A) ID 10001',
    priceFull: '$1199',
    priceDiscount: '$1099',
    description1: 'Screen/6.5" OLED',
    description2: 'Capacity/64 GB',
    description3: 'Ram/4 GB',
    textAbout: 'And then there was Pro/A transformative triple‑camera system that adds tons of capability without complexity./An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro./Camera/Meet the first triple‑camera system to combine cutting‑edge technology with the legendary simplicity of iPhone. Capture up to four times more scene. Get beautiful images in drastically lower light. Shoot the highest‑quality video in a smartphone — then edit with the same tools you love for photos. You’ve never shot with anything like it./Shoot it. Flip it. Zoom it. Crop it. Cut it. Light it. Tweak it. Love it./iPhone 11 Pro lets you capture videos that are beautifully true to life, with greater detail and smoother motion. Epic processing power means it can shoot 4K video with extended dynamic range and cinematic video stabilization — all at 60 fps. You get more creative control, too, with four times more scene and powerful new editing tools to play with.',
    tehcSpecs: 'Screen/6.5” OLED/Resolution/2688x1242/Processor/Apple A113 Bionic/RAM/3 GB/Built in memory/64 GB/Camera/12 Mp + 12 Mp + 12 Mp (Triple)/Zoom/Optical, 2x/Cell/GSM, LTE, UMTS',
    like: false,
    addedToCart: false,
  },
  {
    id: 10017,
    picsArray: [
      "./img/products/folder1/newPhone2.svg",
      "./img/products/folder1/newImg1.svg",
      "./img/products/folder1/image8.svg",
      "./img/products/folder1/newImg2.svg",
      "./img/products/folder1/newImg1.svg",
    ],
    picsArray2: [
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
    ],
    picsArray3: [
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
    ],
    picsArray4: [
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
    ],
    name: 'Apple iPhone 19 128GB Purple (iMT9G2FS/A)',
    priceFull: '$899',
    priceDiscount: '$799',
    description1: 'Screen/6.2" OLED',
    description2: 'Capacity/128 GB',
    description3: 'Ram/4 GB',
    textAbout: 'And then there was Pro/A transformative triple‑camera system that adds tons of capability without complexity./An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro./Camera/Meet the first triple‑camera system to combine cutting‑edge technology with the legendary simplicity of iPhone. Capture up to four times more scene. Get beautiful images in drastically lower light. Shoot the highest‑quality video in a smartphone — then edit with the same tools you love for photos. You’ve never shot with anything like it./Shoot it. Flip it. Zoom it. Crop it. Cut it. Light it. Tweak it. Love it./iPhone 11 Pro lets you capture videos that are beautifully true to life, with greater detail and smoother motion. Epic processing power means it can shoot 4K video with extended dynamic range and cinematic video stabilization — all at 60 fps. You get more creative control, too, with four times more scene and powerful new editing tools to play with.',
    tehcSpecs: 'Screen/6.2” OLED/Resolution/2688x1242/Processor/Apple A00 Bionic/RAM/4 GB/Built in memory/128 GB/Camera/66 Mp + 65 Mp + 99 Mp (Triple)/Zoom/Optical, 9x/Cell/GSM, LTE, UMTS',
    like: false,
    addedToCart: false,
  },
  {
    id: 10018,
    picsArray: [
      "./img/products/folder1/newPhone3.svg",
      "./img/products/folder1/newImg1.svg",
      "./img/products/folder1/image8.svg",
      "./img/products/folder1/newImg2.svg",
      "./img/products/folder1/newImg1.svg",
    ],
    picsArray2: [
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
    ],
    picsArray3: [
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
    ],
    picsArray4: [
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
    ],
    name: 'Apple iPhone Xs 64GB Silver (iMT9G2FS/A)',
    priceFull: '$899',
    priceDiscount: '$799',
    description1: 'Screen/5.8" GB',
    description2: 'Capacity/64 GB',
    description3: 'Ram/4 GB',
    textAbout: 'And then there was Pro/A transformative triple‑camera system that adds tons of capability without complexity./An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro./Camera/Meet the first triple‑camera system to combine cutting‑edge technology with the legendary simplicity of iPhone. Capture up to four times more scene. Get beautiful images in drastically lower light. Shoot the highest‑quality video in a smartphone — then edit with the same tools you love for photos. You’ve never shot with anything like it./Shoot it. Flip it. Zoom it. Crop it. Cut it. Light it. Tweak it. Love it./iPhone 11 Pro lets you capture videos that are beautifully true to life, with greater detail and smoother motion. Epic processing power means it can shoot 4K video with extended dynamic range and cinematic video stabilization — all at 60 fps. You get more creative control, too, with four times more scene and powerful new editing tools to play with.',
    tehcSpecs: 'Screen/5.8” OLED/Resolution/2688x1242/Processor/Apple A12 Bionic/RAM/4 GB/Built in memory/64 GB/Camera/76 Mp + 82 Mp + 92 Mp (Triple)/Zoom/Optical, 2x/Cell/GSM, LTE, UMTS',
    like: false,
    addedToCart: false,
  },
  {
    id: 10019,
    picsArray: [
      "./img/products/folder1/newPhone4.svg",
      "./img/products/folder1/newImg1.svg",
      "./img/products/folder1/image8.svg",
      "./img/products/folder1/newImg2.svg",
      "./img/products/folder1/newImg1.svg",
    ],
    picsArray2: [
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
    ],
    picsArray3: [
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
    ],
    picsArray4: [
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
    ],
    name: 'Apple iPhone 2 Pro Max 512GB Midnight Green (iMT9G2FS/A)',
    priceFull: '',
    priceDiscount: '$1299',
    description1: 'Screen/6.5" OLED',
    description2: 'Capacity/512 GB',
    description3: 'Ram/4 GB',
    textAbout: 'And then there was Pro/A transformative triple‑camera system that adds tons of capability without complexity./An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro./Camera/Meet the first triple‑camera system to combine cutting‑edge technology with the legendary simplicity of iPhone. Capture up to four times more scene. Get beautiful images in drastically lower light. Shoot the highest‑quality video in a smartphone — then edit with the same tools you love for photos. You’ve never shot with anything like it./Shoot it. Flip it. Zoom it. Crop it. Cut it. Light it. Tweak it. Love it./iPhone 11 Pro lets you capture videos that are beautifully true to life, with greater detail and smoother motion. Epic processing power means it can shoot 4K video with extended dynamic range and cinematic video stabilization — all at 60 fps. You get more creative control, too, with four times more scene and powerful new editing tools to play with.',
    tehcSpecs: 'Screen/6.5” OLED/Resolution/2688x1242/Processor/Apple A10 Bionic/RAM/4 GB/Built in memory/512 GB/Camera/69 Mp + 88 Mp + 99 Mp (Triple)/Zoom/Optical, 2x/Cell/GSM, LTE, UMTS',
    like: false,
    addedToCart: false,
  },
  {
    id: 10020,
    picsArray: [
      "./img/products/folder1/newPhone5.svg",
      "./img/products/folder1/newImg1.svg",
      "./img/products/folder1/image8.svg",
      "./img/products/folder1/newImg2.svg",
      "./img/products/folder1/newImg1.svg",
    ],
    picsArray2: [
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
    ],
    picsArray3: [
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
    ],
    picsArray4: [
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
    ],
    name: 'Apple iPhone 113 128GB (Product) Red (iMT9G2FS/A)',
    priceFull: '',
    priceDiscount: '$999',
    description1: 'Screen/6.2" OLED',
    description2: 'Capacity/128 GB',
    description3: 'Ram/4 GB',
    textAbout: 'And then there was Pro/A transformative triple‑camera system that adds tons of capability without complexity./An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro./Camera/Meet the first triple‑camera system to combine cutting‑edge technology with the legendary simplicity of iPhone. Capture up to four times more scene. Get beautiful images in drastically lower light. Shoot the highest‑quality video in a smartphone — then edit with the same tools you love for photos. You’ve never shot with anything like it./Shoot it. Flip it. Zoom it. Crop it. Cut it. Light it. Tweak it. Love it./iPhone 11 Pro lets you capture videos that are beautifully true to life, with greater detail and smoother motion. Epic processing power means it can shoot 4K video with extended dynamic range and cinematic video stabilization — all at 60 fps. You get more creative control, too, with four times more scene and powerful new editing tools to play with.',
    tehcSpecs: 'Screen/6.2” OLED/Resolution/2688x1242/Processor/Apple A182 Shmionic/RAM/4 GB/Built in memory/128 GB/Camera/55 Mp + 88 Mp + 99 Mp (Triple)/Zoom/Optical, 9x/Cell/GSM, LTE, UMTS',
    like: false,
    addedToCart: false,
  },
  {
    id: 10021,
    picsArray: [
      "./img/products/folder1/newPhone1.svg",
      "./img/products/folder1/newImg1.svg",
      "./img/products/folder1/image8.svg",
      "./img/products/folder1/newImg2.svg",
      "./img/products/folder1/newImg1.svg",
    ],
    picsArray2: [
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
    ],
    picsArray3: [
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
    ],
    picsArray4: [
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
    ],
    name: 'Apple iPhone 11 Pro Max 64GB Gold (iMT9G2FS/A) ID 10001',
    priceFull: '$1199',
    priceDiscount: '$1099',
    description1: 'Screen/6.5" OLED',
    description2: 'Capacity/64 GB',
    description3: 'Ram/4 GB',
    textAbout: 'And then there was Pro/A transformative triple‑camera system that adds tons of capability without complexity./An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro./Camera/Meet the first triple‑camera system to combine cutting‑edge technology with the legendary simplicity of iPhone. Capture up to four times more scene. Get beautiful images in drastically lower light. Shoot the highest‑quality video in a smartphone — then edit with the same tools you love for photos. You’ve never shot with anything like it./Shoot it. Flip it. Zoom it. Crop it. Cut it. Light it. Tweak it. Love it./iPhone 11 Pro lets you capture videos that are beautifully true to life, with greater detail and smoother motion. Epic processing power means it can shoot 4K video with extended dynamic range and cinematic video stabilization — all at 60 fps. You get more creative control, too, with four times more scene and powerful new editing tools to play with.',
    tehcSpecs: 'Screen/6.5” OLED/Resolution/2688x1242/Processor/Apple A12 Bionic/RAM/3 GB/Built in memory/64 GB/Camera/12 Mp + 12 Mp + 12 Mp (Triple)/Zoom/Optical, 2x/Cell/GSM, LTE, UMTS',
    like: false,
    addedToCart: false,
  },
  {
    id: 10022,
    picsArray: [
      "./img/products/folder1/newPhone2.svg",
      "./img/products/folder1/newImg1.svg",
      "./img/products/folder1/image8.svg",
      "./img/products/folder1/newImg2.svg",
      "./img/products/folder1/newImg1.svg",
    ],
    picsArray2: [
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
    ],
    picsArray3: [
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
    ],
    picsArray4: [
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
    ],
    name: 'Apple iPhone 19 128GB Purple (iMT9G2FS/A)',
    priceFull: '$899',
    priceDiscount: '$799',
    description1: 'Screen/6.2" OLED',
    description2: 'Capacity/128 GB',
    description3: 'Ram/4 GB',
    textAbout: 'And then there was Pro/A transformative triple‑camera system that adds tons of capability without complexity./An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro./Camera/Meet the first triple‑camera system to combine cutting‑edge technology with the legendary simplicity of iPhone. Capture up to four times more scene. Get beautiful images in drastically lower light. Shoot the highest‑quality video in a smartphone — then edit with the same tools you love for photos. You’ve never shot with anything like it./Shoot it. Flip it. Zoom it. Crop it. Cut it. Light it. Tweak it. Love it./iPhone 11 Pro lets you capture videos that are beautifully true to life, with greater detail and smoother motion. Epic processing power means it can shoot 4K video with extended dynamic range and cinematic video stabilization — all at 60 fps. You get more creative control, too, with four times more scene and powerful new editing tools to play with.',
    tehcSpecs: 'Screen/6.2” OLED/Resolution/2688x1242/Processor/Apple A1276 Bionic/RAM/4 GB/Built in memory/128 GB/Camera/66 Mp + 65 Mp + 99 Mp (Triple)/Zoom/Optical, 9x/Cell/GSM, LTE, UMTS',
    like: false,
    addedToCart: false,
  },
  {
    id: 10023,
    picsArray: [
      "./img/products/folder1/newPhone3.svg",
      "./img/products/folder1/newImg1.svg",
      "./img/products/folder1/image8.svg",
      "./img/products/folder1/newImg2.svg",
      "./img/products/folder1/newImg1.svg",
    ],
    picsArray2: [
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
    ],
    picsArray3: [
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
    ],
    picsArray4: [
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
    ],
    name: 'Apple iPhone Xs 64GB Silver (iMT9G2FS/A)',
    priceFull: '$899',
    priceDiscount: '$799',
    description1: 'Screen/5.8" GB',
    description2: 'Capacity/64 GB',
    description3: 'Ram/4 GB',
    textAbout: 'And then there was Pro/A transformative triple‑camera system that adds tons of capability without complexity./An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro./Camera/Meet the first triple‑camera system to combine cutting‑edge technology with the legendary simplicity of iPhone. Capture up to four times more scene. Get beautiful images in drastically lower light. Shoot the highest‑quality video in a smartphone — then edit with the same tools you love for photos. You’ve never shot with anything like it./Shoot it. Flip it. Zoom it. Crop it. Cut it. Light it. Tweak it. Love it./iPhone 11 Pro lets you capture videos that are beautifully true to life, with greater detail and smoother motion. Epic processing power means it can shoot 4K video with extended dynamic range and cinematic video stabilization — all at 60 fps. You get more creative control, too, with four times more scene and powerful new editing tools to play with.',
    tehcSpecs: 'Screen/5.8” OLED/Resolution/2688x1242/Processor/Apple A12 Bionic/RAM/4 GB/Built in memory/64 GB/Camera/76 Mp + 82 Mp + 92 Mp (Triple)/Zoom/Optical, 2x/Cell/GSM, LTE, UMTS',
    like: false,
    addedToCart: false,
  },
  {
    id: 10024,
    picsArray: [
      "./img/products/folder1/newPhone4.svg",
      "./img/products/folder1/newImg1.svg",
      "./img/products/folder1/image8.svg",
      "./img/products/folder1/newImg2.svg",
      "./img/products/folder1/newImg1.svg",
    ],
    picsArray2: [
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
    ],
    picsArray3: [
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
    ],
    picsArray4: [
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
    ],
    name: 'Apple iPhone 2 Pro Max 512GB Midnight Green (iMT9G2FS/A)',
    priceFull: '',
    priceDiscount: '$1299',
    description1: 'Screen/6.5" OLED',
    description2: 'Capacity/512 GB',
    description3: 'Ram/4 GB',
    textAbout: 'And then there was Pro/A transformative triple‑camera system that adds tons of capability without complexity./An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro./Camera/Meet the first triple‑camera system to combine cutting‑edge technology with the legendary simplicity of iPhone. Capture up to four times more scene. Get beautiful images in drastically lower light. Shoot the highest‑quality video in a smartphone — then edit with the same tools you love for photos. You’ve never shot with anything like it./Shoot it. Flip it. Zoom it. Crop it. Cut it. Light it. Tweak it. Love it./iPhone 11 Pro lets you capture videos that are beautifully true to life, with greater detail and smoother motion. Epic processing power means it can shoot 4K video with extended dynamic range and cinematic video stabilization — all at 60 fps. You get more creative control, too, with four times more scene and powerful new editing tools to play with.',
    tehcSpecs: 'Screen/6.5” OLED/Resolution/2688x1242/Processor/Apple A12 Bionic/RAM/4 GB/Built in memory/512 GB/Camera/69 Mp + 88 Mp + 99 Mp (Triple)/Zoom/Optical, 2x/Cell/GSM, LTE, UMTS',
    like: false,
    addedToCart: false,
  },
  {
    id: 10025,
    picsArray: [
      "./img/products/folder1/newPhone5.svg",
      "./img/products/folder1/newImg1.svg",
      "./img/products/folder1/image8.svg",
      "./img/products/folder1/newImg2.svg",
      "./img/products/folder1/newImg1.svg",
    ],
    picsArray2: [
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
    ],
    picsArray3: [
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
    ],
    picsArray4: [
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
    ],
    name: 'Apple iPhone 113 128GB (Product) Red (iMT9G2FS/A)',
    priceFull: '',
    priceDiscount: '$999',
    description1: 'Screen/6.2" OLED',
    description2: 'Capacity/128 GB',
    description3: 'Ram/4 GB',
    textAbout: 'And then there was Pro/A transformative triple‑camera system that adds tons of capability without complexity./An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro./Camera/Meet the first triple‑camera system to combine cutting‑edge technology with the legendary simplicity of iPhone. Capture up to four times more scene. Get beautiful images in drastically lower light. Shoot the highest‑quality video in a smartphone — then edit with the same tools you love for photos. You’ve never shot with anything like it./Shoot it. Flip it. Zoom it. Crop it. Cut it. Light it. Tweak it. Love it./iPhone 11 Pro lets you capture videos that are beautifully true to life, with greater detail and smoother motion. Epic processing power means it can shoot 4K video with extended dynamic range and cinematic video stabilization — all at 60 fps. You get more creative control, too, with four times more scene and powerful new editing tools to play with.',
    tehcSpecs: 'Screen/6.2” OLED/Resolution/2688x1242/Processor/Apple A182 Shmionic/RAM/4 GB/Built in memory/128 GB/Camera/55 Mp + 88 Mp + 99 Mp (Triple)/Zoom/Optical, 9x/Cell/GSM, LTE, UMTS',
    like: false,
    addedToCart: false,
  },
  {
    id: 10026,
    picsArray: [
      "./img/products/folder1/newPhone1.svg",
      "./img/products/folder1/newImg1.svg",
      "./img/products/folder1/image8.svg",
      "./img/products/folder1/newImg2.svg",
      "./img/products/folder1/newImg1.svg",
    ],
    picsArray2: [
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
    ],
    picsArray3: [
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
    ],
    picsArray4: [
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
    ],
    name: 'Apple iPhone 11 Pro Max 64GB Gold (iMT9G2FS/A) ID 10001',
    priceFull: '$1199',
    priceDiscount: '$1099',
    description1: 'Screen/6.5" OLED',
    description2: 'Capacity/64 GB',
    description3: 'Ram/4 GB',
    textAbout: 'And then there was Pro/A transformative triple‑camera system that adds tons of capability without complexity./An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro./Camera/Meet the first triple‑camera system to combine cutting‑edge technology with the legendary simplicity of iPhone. Capture up to four times more scene. Get beautiful images in drastically lower light. Shoot the highest‑quality video in a smartphone — then edit with the same tools you love for photos. You’ve never shot with anything like it./Shoot it. Flip it. Zoom it. Crop it. Cut it. Light it. Tweak it. Love it./iPhone 11 Pro lets you capture videos that are beautifully true to life, with greater detail and smoother motion. Epic processing power means it can shoot 4K video with extended dynamic range and cinematic video stabilization — all at 60 fps. You get more creative control, too, with four times more scene and powerful new editing tools to play with.',
    tehcSpecs: 'Screen/6.5” OLED/Resolution/2688x1242/Processor/Apple A1 Bionic/RAM/3 GB/Built in memory/64 GB/Camera/12 Mp + 12 Mp + 12 Mp (Triple)/Zoom/Optical, 2x/Cell/GSM, LTE, UMTS',
    like: false,
    addedToCart: false,
  },
  {
    id: 10027,
    picsArray: [
      "./img/products/folder1/newPhone2.svg",
      "./img/products/folder1/newImg1.svg",
      "./img/products/folder1/image8.svg",
      "./img/products/folder1/newImg2.svg",
      "./img/products/folder1/newImg1.svg",
    ],
    picsArray2: [
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
    ],
    picsArray3: [
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
    ],
    picsArray4: [
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
    ],
    name: 'Apple iPhone 19 128GB Purple (iMT9G2FS/A)',
    priceFull: '$899',
    priceDiscount: '$799',
    description1: 'Screen/6.2" OLED',
    description2: 'Capacity/128 GB',
    description3: 'Ram/4 GB',
    textAbout: 'And then there was Pro/A transformative triple‑camera system that adds tons of capability without complexity./An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro./Camera/Meet the first triple‑camera system to combine cutting‑edge technology with the legendary simplicity of iPhone. Capture up to four times more scene. Get beautiful images in drastically lower light. Shoot the highest‑quality video in a smartphone — then edit with the same tools you love for photos. You’ve never shot with anything like it./Shoot it. Flip it. Zoom it. Crop it. Cut it. Light it. Tweak it. Love it./iPhone 11 Pro lets you capture videos that are beautifully true to life, with greater detail and smoother motion. Epic processing power means it can shoot 4K video with extended dynamic range and cinematic video stabilization — all at 60 fps. You get more creative control, too, with four times more scene and powerful new editing tools to play with.',
    tehcSpecs: 'Screen/6.2” OLED/Resolution/2688x1242/Processor/Apple A1276 Bionic/RAM/4 GB/Built in memory/128 GB/Camera/66 Mp + 65 Mp + 99 Mp (Triple)/Zoom/Optical, 9x/Cell/GSM, LTE, UMTS',
    like: false,
    addedToCart: false,
  },
  {
    id: 10028,
    picsArray: [
      "./img/products/folder1/newPhone3.svg",
      "./img/products/folder1/newImg1.svg",
      "./img/products/folder1/image8.svg",
      "./img/products/folder1/newImg2.svg",
      "./img/products/folder1/newImg1.svg",
    ],
    picsArray2: [
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
    ],
    picsArray3: [
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
    ],
    picsArray4: [
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
    ],
    name: 'Apple iPhone Xs 64GB Silver (iMT9G2FS/A)',
    priceFull: '$899',
    priceDiscount: '$799',
    description1: 'Screen/5.8" GB',
    description2: 'Capacity/64 GB',
    description3: 'Ram/4 GB',
    textAbout: 'And then there was Pro/A transformative triple‑camera system that adds tons of capability without complexity./An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro./Camera/Meet the first triple‑camera system to combine cutting‑edge technology with the legendary simplicity of iPhone. Capture up to four times more scene. Get beautiful images in drastically lower light. Shoot the highest‑quality video in a smartphone — then edit with the same tools you love for photos. You’ve never shot with anything like it./Shoot it. Flip it. Zoom it. Crop it. Cut it. Light it. Tweak it. Love it./iPhone 11 Pro lets you capture videos that are beautifully true to life, with greater detail and smoother motion. Epic processing power means it can shoot 4K video with extended dynamic range and cinematic video stabilization — all at 60 fps. You get more creative control, too, with four times more scene and powerful new editing tools to play with.',
    tehcSpecs: 'Screen/5.8” OLED/Resolution/2688x1242/Processor/Apple A19 Bionic/RAM/42 GB/Built in memory/164 GB/Camera/76 Mp + 82 Mp + 92 Mp (Triple)/Zoom/Optical, 2x/Cell/GSM, LTE, UMTS',
    like: false,
    addedToCart: false,
  },
  {
    id: 10029,
    picsArray: [
      "./img/products/folder1/newPhone4.svg",
      "./img/products/folder1/newImg1.svg",
      "./img/products/folder1/image8.svg",
      "./img/products/folder1/newImg2.svg",
      "./img/products/folder1/newImg1.svg",
    ],
    picsArray2: [
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
      "./img/products/folder1/image2_2.png",
    ],
    picsArray3: [
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
      "./img/products/folder1/image2_3.png",
    ],
    picsArray4: [
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
      "./img/products/folder1/image2_4.png",
    ],
    name: 'Apple iPhone 2 Pro Max 512GB Midnight Green (iMT9G2FS/A)',
    priceFull: '',
    priceDiscount: '$1299',
    description1: 'Screen/6.5" OLED',
    description2: 'Capacity/512 GB',
    description3: 'Ram/4 GB',
    textAbout: 'And then there was Pro/A transformative triple‑camera system that adds tons of capability without complexity./An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro./Camera/Meet the first triple‑camera system to combine cutting‑edge technology with the legendary simplicity of iPhone. Capture up to four times more scene. Get beautiful images in drastically lower light. Shoot the highest‑quality video in a smartphone — then edit with the same tools you love for photos. You’ve never shot with anything like it./Shoot it. Flip it. Zoom it. Crop it. Cut it. Light it. Tweak it. Love it./iPhone 11 Pro lets you capture videos that are beautifully true to life, with greater detail and smoother motion. Epic processing power means it can shoot 4K video with extended dynamic range and cinematic video stabilization — all at 60 fps. You get more creative control, too, with four times more scene and powerful new editing tools to play with.',
    tehcSpecs: 'Screen/6.5” OLED/Resolution/2688x1242/Processor/Apple A112 Bionic/RAM/42 GB/Built in memory/5312 GB/Camera/69 Mp + 88 Mp + 99 Mp (Triple)/Zoom/Optical, 2x/Cell/GSM, LTE, UMTS',
    like: false,
    addedToCart: false,
  },
]
