export enum Colors {
  BLACK = 'black',
  GREEN = 'green',
  YELLOW = 'yellow',
  WHITE = 'white',
  PURPLE = 'purple',
  RED = 'red',
  SPACE_GRAY = 'spacegray',
  MIDNIGHT_GREEN = 'midnightgreen',
  SILVER = 'silver',
  GOLD = 'gold',
  ROSE_GOLD = 'rosegold',
  CORAL = 'coral',
  MIDNIGHT = 'midnight',
  SPACE_BLACK = 'spaceblack',
  BLUE = 'blue',
  GRAPHITE = 'graphite',
  SIERRA_BLUE = 'sierrablue',
  SKY_BLUE = 'skyblue',
  STARLIGHT = 'starlight',
  PINK = 'pink',
}
