export enum Color {
  GREEN = 'green',
  SKYBLUE = 'sky-blue',
  SPACEGRAY = 'spacegray',
  SPACE_GRAY = 'space gray',
  SPACE_GRAY_DASH = 'space-gray',
  STARLIGHT = 'starlight',
  PINK = 'pink',
  GOLD = 'gold',
  SILVER = 'silver',
  BLACK = 'black',
  MIDNIGHTGREEN = 'midnightgreen',
  RED = 'red',
  WHITE = 'white',
  PURPLE = 'purple',
  YELLOW = 'yellow',
  CORAL = 'coral',
  ROSEGOLD = 'rosegold',
  SPACEBLACK = 'spaceblack',
  MIDNIGHT = 'midnight',
  SIERRABLUE = 'sierrablue',
  GRAPHITE = 'graphite',
}
