export const colorMap: { [key: string]: string } = {
  black: 'var(--black-button-color)',
  green: 'var(--green-button-color)',
  yellow: 'var(--yellow-button-color)',
  white: 'var(--white-button-color)',
  purple: 'var(--purple-button-color)',
  red: 'var(--red-button-color)',
  gold: 'var(--gold-button-color)',
  silver: 'var(--silver-button-color)',
  midnightgreen: 'var(--midnightgreen-button-color)',
  spacegray: 'var(--spacegray-button-color)',
  rosegold: 'var(--rosegold-button-color)',
  coral: 'var(--coral-button-color)',
  skyblue: 'var(--skyblue-button-color)',
  starlight: 'var(--starlight-button-color)',
  pink: 'var(--pink-button-color)',
  blue: 'var(--blue-button-color)',
  midnight: 'var(--midnight-button-color)',
  graphite: 'var(--graphite-button-color)',
  sierrablue: 'var(--sierrablue-button-color)',
  spaceblack: 'var(--spaceblack-button-color)',
  'space gray': 'var(--spacegray-button-color)',
  'sky blue': 'var(--skyblue-button-color)',
  'rose gold': 'var(--rosegold-button-color)',
};
