export enum Colors {
  black = 'black',
  gold = 'gold',
  yellow = 'yellow',
  green = 'green',
  midnightgreen = '#004953',
  silver = 'silver',
  spacegray = '#686868',
  red = 'red',
  white = 'white',
  purple = 'purple',
  coral = 'coral',
  rosegold = '#B76E79',
  midnight = '#2C3E50',
  spaceblack = '#0A0A0A',
  blue = 'blue',
  pink = 'pink',
  sierrablue = '#376F89',
  graphite = '#4A4A4A',
  skyblue = 'sky-blue',
  starlight = '#C7C7CC',
}
