export enum IconType {
  ARROW_DOWN = 'icon__arrow-down',
  ARROW_DOWN_DISABLED = 'icon__arrow-down--disabled',
  ARROW_LEFT = 'icon__arrow-left',
  ARROW_LEFT_DISABLED = 'icon__arrow-left--disabled',
  ARROW_RIGHT = 'icon__arrow-right',
  ARROW_RIGHT_DISABLED = 'icon__arrow-right--disabled',
  ARROW_UP = 'icon__arrow-up',
  ARROW_UP_DISABLED = 'icon__arrow-up--disabled',
  CART = 'icon__cart',
  CLOSE = 'icon__close',
  CLOSE_DISABLED = 'icon__close--disabled',
  CROSS = 'icon__cross',
  FAVORITE = 'icon__favorite',
  FAVORITE_FILLED = 'icon__favorite--active',
  HOME = 'icon__home',
  MENU_BURGER = 'icon__menu-burger',
  MINUS = 'icon__minus',
  MINUS_DISABLED = 'icon__minus--disabled',
  PLUS = 'icon__plus',
  SEARCH = 'icon__search',
}
