export enum IconType {
  ARROW_UP = 'icon__arrow-up',
  ARROW_UP_DISABLED = 'icon__arrow-up--disabled',
  ARROW_DOWN = 'icon__arrow-down',
  ARROW_DOWN_DISABLED = 'icon__arrow-down--disabled',
  ARROW_LEFT = 'icon__arrow-left',
  ARROW_LEFT_DISABLED = 'icon__arrow-left--disabled',
  ARROW_RIGHT = 'icon__arrow-right',
  ARROW_RIGHT_DISABLED = 'icon__arrow-right--disabled',
  FAVORITE = 'icon__favorite',
  FAVORITE_SELECTED = 'icon__favorite--selected',
  HOME = 'icon__home',
  CART = 'icon__cart',
  CROSS = 'icon__cross',
  CROSS_DISABLED = 'icon__cross--disabled',
  MENU = 'icon__menu',
  MINUS = 'icon__minus',
  MINUS_DISABLED = 'icon__minus--disabled',
  PLUS = 'icon__plus',
  SEARCH = 'icon__search',
}
