export enum NavLinks {
  NewArrivals = 'New arrivals',
  AllGender = 'All gender',
  LookBook = 'Look book',
  Search = 'Search',
  Logo = 'icon__image--logo',
  Delivering = 'Delivering',
  Bag = 'Bag',
  WishList = 'Wish list',
  Profile = 'Profile',
  Burger = 'icon__image--burger',
  NotFound = 'icon__image--404',
  ContactUs = 'Contact us',
  Instagram = 'icon__image--instagram',
  TikTok = 'icon__image--tikTok',
  Pinterest = 'icon__image--pinterest',
}
