export type PhoneDetails = {
  id: string,
  namespaceId: string,
  name: string,
  capacity: string,
  capacityAvailable: string[],
  priceRegular: number,
  priceDiscount: number,
  colorsAvailable: string[],
  color: string,
  images: string[],
  description: [
    { title: string, text: string[] },
    { title: string, text: string[] },
    { title: string, text: string[] },
  ],
  screen: string,
  resolution: string,
  processor: string,
  ram: string,
  camera: string,
  zoom: string,
  cell: string[],
  // old api
  additionalFeatures: string,
  android: {
    os: string,
    ui: string,
  },
  availability: string[],
  battery: {
    standbyTime: string,
    talkTime: string,
    type: string,
  },
  connectivity: {
    bluetooth: string,
    cell: string,
    gps: string,
    infrared: boolean,
    wifi: string,
  },
  display: {
    screenResolution: string,
    screenSize: string,
    touchScreen: boolean,
  },
  hardware: {
    accelerometer: boolean,
    audioJack: string,
    cpu: string,
    fmRadio: boolean,
    physicalKeyboard: boolean,
    usb: string,
  },
  sizeAndWeight: {
    dimensions: string[],
    weight: string,
  },
  storage: {
    flash: string,
    ram: string,
  },
};
