import { ProductDescription } from './ProductDescription';

export interface Product {
  capacity: string,
  color: string,
  category: string,
  fullPrice: number,
  itemId: string,
  year: number,
  phoneId: string,
  age: number,
  id: string,
  type: string,
  image: string,
  name: string,
  snippet: string,
  price: number,
  discount: number,
  screen: string,
  ram: string,
  camera: string,
  capacityAvailable: string[],
  cell: string[],
  colorsAvailable: string[],
  description: ProductDescription [],
  images: string [],
  namespaceId: string,
  priceDiscount: number,
  priceRegular: number,
  processor: string,
  resolution: string,
  zoom: string,
}
