export const colorMap: Record<string, string> = {
  black: 'black',
  gold: 'gold',
  green: 'green',
  midnight: 'midnightblue',
  midnightgreen: '#355E3B',
  silver: 'silver',
  spacegray: 'gray',
  white: 'white',
  yellow: 'yellow',
  red: 'red',
  purple: 'purple',
  coral: 'coral',
  rosegold: '#E0BFB8',
  blue: 'blue',
  spaceblack: 'black',
  graphite: '#383428',
  sierrablue: '#BFDAF7',
  pink: 'pink',
  starlight: '#F8F9EC',
  'rose gold': '#E0BFB8',
  'sky blue': '#87CEEB',
  'space gray': 'gray',
};
