export enum StrCode {
  WelcomeMessage = 'WELCOME_MESSAGE',
  NewModels = 'NEW_MODELS',
  Screen = 'SCREEN',
  Capacity = 'CAPACITY',
  Ram = 'RAM',
  AddToCard = 'ADD_TO_CART',
  ShopByCategory = 'SHOP_BY_CATEGORY',
  MobilePhones = 'MOBILE_PHONES',
  Models = 'MODELS',
  Tablets = 'TABLETS',
  Accessories = 'ACCESSORIES',
  HotPrices = 'HOT_PRICES',
  Contacts = 'CONTACTS',
  Rights = 'RIGHTS',
  BackToTop = 'BACK_TO_TOP',
  Theme = 'THEME',
  Language = 'LANGUAGE',
  Home = 'HOME',
  Phones = 'PHONES',
}
