export type Details = {
  id: string;
  category: string;
  namespaceId: string;
  name: string;
  capacityAvailable: string[];
  camera: string;
  capacity: string;
  cell: string[];
  color: string;
  colorsAvailable: string[];
  description: {};
  images: string[];
  priceDiscount: number;
  priceRegular: number;
  processor: string;
  ram: string;
  resolution: string;
  screen: string;
  zoom: string;
};
