"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _blog_card from './blog-card.bones.json'

registerBones({
  "blog-card": _blog_card,
})
