'use client';
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js';

import _ProductCard from './ProductCard.bones.json';

registerBones({
  ProductCard: _ProductCard,
});
