import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import './index.scss';
import App from './App';
import { HashRouter, Navigate, Route, Routes } from 'react-router-dom';
import { PhonePage } from './pages/PhonePage';
import { HomePage } from './modules/HomePage';
import { NotFoundPage } from './pages/NotFoundPage';
import { ScrollToTop } from './components/ScrollToTop';
import './i18n/i18n';
import { ProductDetailsPage } from './pages/ProductDetailsPage';
createRoot(document.getElementById('root')).render(_jsxs(HashRouter, { children: [_jsx(ScrollToTop, {}), _jsx(Routes, { children: _jsxs(Route, { path: "/", element: _jsx(App, {}), children: [_jsx(Route, { index: true, element: _jsx(HomePage, {}) }), _jsx(Route, { path: "home", element: _jsx(Navigate, { to: "/", replace: true }) }), _jsxs(Route, { path: "phones", children: [_jsx(Route, { index: true, element: _jsx(PhonePage, {}) }), _jsx(Route, { path: ":productId?", element: _jsx(ProductDetailsPage, {}) })] }), _jsx(Route, { path: "*", element: _jsx(NotFoundPage, {}) })] }) })] }));
