export const mobiles = [
  {
    id: '51',
    category: 'phones',
    phoneId: 'apple-iphone-11-128gb-green',
    itemId: 'apple-iphone-11-128gb-green',
    name: 'Apple iPhone 11 128GB Green',
    fullPrice: 1100,
    price: 1050,
    screen: "6.1' IPS",
    capacity: '128GB',
    color: 'green',
    ram: '4GB',
    year: 2019,
    image: 'img/phones/apple-iphone-11/green/00.jpg',
  },
  {
    id: '52',
    category: 'phones',
    phoneId: 'apple-iphone-11-128gb-white',
    itemId: 'apple-iphone-11-128gb-white',
    name: 'Apple iPhone 11 128GB White',
    fullPrice: 1100,
    price: 1050,
    screen: "6.1' IPS",
    capacity: '128GB',
    color: 'white',
    ram: '4GB',
    year: 2019,
    image: 'img/phones/apple-iphone-11/white/00.jpg',
  },
  {
    id: '53',
    category: 'phones',
    phoneId: 'apple-iphone-11-256gb-black',
    itemId: 'apple-iphone-11-256gb-black',
    name: 'Apple iPhone 11 256GB Black',
    fullPrice: 1172,
    price: 1115,
    screen: "6.1' IPS",
    capacity: '256GB',
    color: 'black',
    ram: '4GB',
    year: 2019,
    image: 'img/phones/apple-iphone-11/black/00.jpg',
  },
  {
    id: '54',
    category: 'phones',
    phoneId: 'apple-iphone-11-256gb-white',
    itemId: 'apple-iphone-11-256gb-white',
    name: 'Apple iPhone 11 256GB White',
    fullPrice: 1172,
    price: 1115,
    screen: "6.1' IPS",
    capacity: '256GB',
    color: 'white',
    ram: '4GB',
    year: 2019,
    image: 'img/phones/apple-iphone-11/white/00.jpg',
  },
  {
    id: '55',
    category: 'phones',
    phoneId: 'apple-iphone-11-pro-64gb-spacegray',
    itemId: 'apple-iphone-11-pro-64gb-spacegray',
    name: 'Apple iPhone 11 Pro 64GB Spacegray',
    fullPrice: 1312,
    price: 1270,
    screen: "5.8' OLED",
    capacity: '64GB',
    color: 'spacegray',
    ram: '4GB',
    year: 2019,
    image: 'img/phones/apple-iphone-11-pro/spacegray/00.jpg',
  },
  {
    id: '56',
    category: 'phones',
    phoneId: 'apple-iphone-11-pro-512gb-midnightgreen',
    itemId: 'apple-iphone-11-pro-512gb-midnightgreen',
    name: 'Apple iPhone 11 Pro 512GB Midnight green',
    fullPrice: 1880,
    price: 1780,
    screen: "5.8' OLED",
    capacity: '512GB',
    color: 'midnightgreen',
    ram: '4GB',
    year: 2019,
    image: 'img/phones/apple-iphone-11-pro/midnightgreen/00.jpg',
  },
  {
    id: '57',
    category: 'phones',
    phoneId: 'apple-iphone-11-pro-max-64gb-gold',
    itemId: 'apple-iphone-11-pro-max-64gb-gold',
    name: 'Apple iPhone 11 Pro Max 64GB Gold',
    fullPrice: 1480,
    price: 1400,
    screen: "6.5' OLED",
    capacity: '64GB',
    color: 'gold',
    ram: '4GB',
    year: 2019,
    image: 'img/phones/apple-iphone-11-pro-max/gold/00.jpg',
  },
  {
    id: '58',
    category: 'phones',
    phoneId: 'apple-iphone-11-pro-max-256gb-silver',
    itemId: 'apple-iphone-11-pro-max-256gb-silver',
    name: 'Apple iPhone 11 Pro Max 256GB Silver',
    fullPrice: 1776,
    price: 1680,
    screen: "6.5' OLED",
    capacity: '256GB',
    color: 'silver',
    ram: '4GB',
    year: 2019,
    image: 'img/phones/apple-iphone-11-pro-max/silver/00.jpg',
  },
  {
    id: '59',
    category: 'phones',
    phoneId: 'apple-iphone-11-pro-max-512gb-midnightgreen',
    itemId: 'apple-iphone-11-pro-max-512gb-midnightgreen',
    name: 'Apple iPhone 11 Pro Max 512GB Midnightgreen',
    fullPrice: 2020,
    price: 1930,
    screen: "6.5' OLED",
    capacity: '512GB',
    color: 'midnightgreen',
    ram: '4GB',
    year: 2019,
    image: 'img/phones/apple-iphone-11-pro-max/midnightgreen/00.jpg',
  },
  {
    id: '60',
    category: 'phones',
    phoneId: 'apple-iphone-xr-128gb-yellow',
    itemId: 'apple-iphone-xr-128gb-yellow',
    name: 'Apple iPhone XR 128GB Yellow',
    fullPrice: 880,
    price: 815,
    screen: "6.1' IPS",
    capacity: '128GB',
    color: 'yellow',
    ram: '3GB',
    year: 2018,
    image: 'img/phones/apple-iphone-xr/yellow/00.jpg',
  },
  {
    id: '61',
    category: 'phones',
    phoneId: 'apple-iphone-7-32gb-silver',
    itemId: 'apple-iphone-7-32gb-silver',
    name: 'Apple iPhone 7 32GB Silver',
    fullPrice: 400,
    price: 375,
    screen: "4.7' IPS",
    capacity: '32GB',
    color: 'silver',
    ram: '2GB',
    year: 2016,
    image: 'img/phones/apple-iphone-7/silver/00.jpg',
  },
  {
    id: '62',
    category: 'phones',
    phoneId: 'apple-iphone-11-256gb-purple',
    itemId: 'apple-iphone-11-256gb-purple',
    name: 'Apple iPhone 11 256GB Purple',
    fullPrice: 1172,
    price: 1115,
    screen: "6.1' IPS",
    capacity: '256GB',
    color: 'purple',
    ram: '4GB',
    year: 2019,
    image: 'img/phones/apple-iphone-11/purple/00.jpg',
  },
  {
    id: '63',
    category: 'phones',
    phoneId: 'apple-iphone-11-pro-max-512gb-gold',
    itemId: 'apple-iphone-11-pro-max-512gb-gold',
    name: 'Apple iPhone 11 Pro Max 512GB Gold',
    fullPrice: 2020,
    price: 1930,
    screen: "6.5' OLED",
    capacity: '512GB',
    color: 'gold',
    ram: '4GB',
    year: 2019,
    image: 'img/phones/apple-iphone-11-pro-max/gold/00.jpg',
  },
  {
    id: '64',
    category: 'phones',
    phoneId: 'apple-iphone-11-64gb-yellow',
    itemId: 'apple-iphone-11-64gb-yellow',
    name: 'Apple iPhone 11 64GB Yellow',
    fullPrice: 932,
    price: 880,
    screen: "6.1' IPS",
    capacity: '64GB',
    color: 'yellow',
    ram: '4GB',
    year: 2019,
    image: 'img/phones/apple-iphone-11/yellow/00.jpg',
  },
  {
    id: '65',
    category: 'phones',
    phoneId: 'apple-iphone-11-pro-256gb-spacegray',
    itemId: 'apple-iphone-11-pro-256gb-spacegray',
    name: 'Apple iPhone 11 Pro 256GB Spacegray',
    fullPrice: 1640,
    price: 1570,
    screen: "5.8' OLED",
    capacity: '256GB',
    color: 'spacegray',
    ram: '4GB',
    year: 2019,
    image: 'img/phones/apple-iphone-11-pro/spacegray/00.jpg',
  },
  {
    id: '66',
    category: 'phones',
    phoneId: 'apple-iphone-8-64gb-silver',
    itemId: 'apple-iphone-8-64gb-silver',
    name: 'Apple iPhone 8 64GB Silver',
    fullPrice: 600,
    price: 550,
    screen: "4.7' IPS",
    capacity: '64GB',
    color: 'silver',
    ram: '2GB',
    year: 2017,
    image: 'img/phones/apple-iphone-8/silver/00.jpg',
  },
  {
    id: '67',
    category: 'phones',
    phoneId: 'apple-iphone-11-128gb-red',
    itemId: 'apple-iphone-11-128gb-red',
    name: 'Apple iPhone 11 128GB Red',
    fullPrice: 1100,
    price: 1050,
    screen: "6.1' IPS",
    capacity: '128GB',
    color: 'red',
    ram: '4GB',
    year: 2019,
    image: 'img/phones/apple-iphone-11/red/00.jpg',
  },
  {
    id: '68',
    category: 'phones',
    phoneId: 'apple-iphone-xs-max-256gb-spacegray',
    itemId: 'apple-iphone-xs-max-256gb-spacegray',
    name: 'Apple iPhone XS Max 256GB Spacegray',
    fullPrice: 1080,
    price: 1000,
    screen: "6.5' OLED",
    capacity: '256GB',
    color: 'spacegray',
    ram: '4GB',
    year: 2018,
    image: 'img/phones/apple-iphone-xs-max/spacegray/00.jpg',
  },
  {
    id: '69',
    category: 'phones',
    phoneId: 'apple-iphone-7-plus-32gb-gold',
    itemId: 'apple-iphone-7-plus-32gb-gold',
    name: 'Apple iPhone 7 Plus 32GB Gold',
    fullPrice: 540,
    price: 500,
    screen: "5.5' IPS",
    capacity: '32GB',
    color: 'gold',
    ram: '3GB',
    year: 2016,
    image: 'img/phones/apple-iphone-7-plus/gold/00.jpg',
  },
  {
    id: '70',
    category: 'phones',
    phoneId: 'apple-iphone-11-pro-64gb-silver',
    itemId: 'apple-iphone-11-pro-64gb-silver',
    name: 'Apple iPhone 11 Pro 64GB Silver',
    fullPrice: 1312,
    price: 1270,
    screen: "5.8' OLED",
    capacity: '64GB',
    color: 'silver',
    ram: '4GB',
    year: 2019,
    image: 'img/phones/apple-iphone-11-pro/silver/00.jpg',
  },
  {
    id: '71',
    category: 'phones',
    phoneId: 'apple-iphone-xr-64gb-yellow',
    itemId: 'apple-iphone-xr-64gb-yellow',
    name: 'Apple iPhone XR 64GB Yellow',
    fullPrice: 712,
    price: 670,
    screen: "6.1' IPS",
    capacity: '64GB',
    color: 'yellow',
    ram: '3GB',
    year: 2018,
    image: 'img/phones/apple-iphone-xr/yellow/00.jpg',
  },
];
