export { ProductPhotos } from './ProductPhotos';
export { ProductColors } from './ProductColors';
export { ProductCapacity } from './ProductCapacity';
export { ProductPrice } from './ProductPrice';
export { ProductActions } from './ProductActions';
export { ProductSpecsMain } from './ProductSpecsMain';
export { ProductAbout } from './ProductAbout';
export { ProductSpecsFull } from './ProductSpecsFull';
export { YouMayLike } from './YouMayLike';
